name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypass
          POSTGRES_DB: shortener
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 코드 내려받기
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: url-service 디렉토리로 이동
        working-directory: ./url-service
        run: echo "확인용"

      - name: 의존성 설치
        working-directory: ./url-service
        run: npm install

      - name: 테스트 실행 (없을 경우 생략됨)
        working-directory: ./url-service
        run: npm test || echo "테스트 없음"
