name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypass
          POSTGRES_DB: shortener
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: DockerHub 로그인
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # url-service
      - name: Install dependencies (url-service)
        working-directory: ./url-service
        run: npm install

      - name: Docker build (url-service)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/url-service:latest ./url-service

      - name: Docker push (url-service)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-service:latest

      # auth-service
      - name: Install dependencies (auth-service)
        working-directory: ./auth-service
        run: npm install

      - name: Docker build (auth-service)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./auth-service

      - name: Docker push (auth-service)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      # redirect-service
      - name: Install dependencies (redirect-service)
        working-directory: ./redirect-service
        run: npm install

      - name: Docker build (redirect-service)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/redirect-service:latest ./redirect-service

      - name: Docker push (redirect-service)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/redirect-service:latest

      # gateway
      - name: Docker build (gateway)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest ./gateway

      - name: Docker push (gateway)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest
